server:
  port: 8080
  servlet:
    context-path: /rose
spring:
  datasource:
    url: jdbc:mysql://192.168.56.4:3316/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #数据库平台
    hibernate:
      ddl-auto: update  #数据库增量更新